# Generated by Django 4.1.2 on 2022-10-26 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0002_alter_article_author_alter_profile_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_post', models.CharField(max_length=20)),
                ('content_post', models.TextField()),
                ('image_post', models.CharField(max_length=1000)),
                ('time_created_post', models.DateTimeField(auto_now_add=True)),
                ('author_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
