# Generated by Django 4.1.2 on 2022-10-27 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_article', to=settings.AUTH_USER_MODEL),
        ),
    ]
