# Generated by Django 4.1.2 on 2022-11-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0004_rename_profile_name_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
